<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
    <SupportedPlatform Include="android" />
    <SupportedPlatform Include="ios" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0' and $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'browser'">
       <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Qimono.Baza.Modeloj" Version="1.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>Qimono.Baza.Bloko</PackageId>
    <Version>1.0.3</Version>
    <Title>Baza Bloko (by QiMono)</Title>
    <Authors>QiMono</Authors>
    <Description>Basic Reusable Components for .NET Apps</Description>
    <PackageLicenseFile>LICENSE-LGPLv3.md</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://qimono76.wordpress.com</PackageProjectUrl>
    <RepositoryUrl>https://github.com/qimono-repos/bloko-baza.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>component,razor, hybrid</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

  <ItemGroup>
    <None Include="LICENSE-LGPLv3.md" Pack="true" PackagePath="" />
  </ItemGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>

